---
deployment:
  tasks:
    – export DEPLOYPATH=/home/webcsosl/public_html/
    – /bin/cp Home.html $DEPLOYPATH
    – /bin/cp ContactUs.html $DEPLOYPATH
    – /bin/cp -R CSS $DEPLOYPATH
    – /bin/cp Websites.html $DEPLOYPATH
    /bin/cp OurServices.html $DEPLOYPATH
